name: JarvisIOS
options:
  bundleIdPrefix: com.jarvis
settings:
  base:
    SWIFT_VERSION: 5.10
targets:
  JarvisIOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/JarvisIOS
    info:
      path: Sources/JarvisIOS/Resources/Info.plist
      properties:
        CFBundleDisplayName: Jarvis
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jarvis.ios
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    scheme:
      testTargets: []
